# Generated by Django 6.0.2 on 2026-02-27 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_eventregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('paysuite_id', models.CharField(blank=True, max_length=64, null=True)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=40, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=64, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('last_webhook_request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('raw_provider_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='events.eventregistration')),
            ],
        ),
    ]
