# Generated by Django 6.0.2 on 2026-02-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('city', models.CharField(choices=[('MAPUTO', 'Maputo'), ('MATOLA', 'Matola')], db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('WEEKLY', 'Weekly Run'), ('LONG', 'Long Run'), ('TRAIL', 'Trail'), ('COLLAB', 'Collab')], db_index=True, max_length=20)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_point_name', models.CharField(max_length=220)),
                ('meeting_point_address', models.CharField(blank=True, max_length=320)),
                ('google_maps_url', models.URLField(blank=True)),
                ('distance_min_km', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('distance_max_km', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pace_min', models.CharField(blank=True, max_length=20)),
                ('pace_max', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='events/posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('start_at',),
                'indexes': [models.Index(fields=['city', 'start_at'], name='events_even_city_b3f740_idx'), models.Index(fields=['event_type', 'start_at'], name='events_even_event_t_2bab82_idx')],
            },
        ),
    ]
