# Generated by Django 6.0.2 on 2026-02-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='meeting_point_name',
            new_name='meeting_point',
        ),
        migrations.RemoveField(
            model_name='event',
            name='distance_max_km',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='google_maps_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='meeting_point_address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pace_max',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pace_min',
        ),
    ]
