# Generated by Django 6.0.2 on 2026-02-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_meeting_point_name_event_meeting_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('WEEKLY', 'Weekly Run'), ('LONG', 'Long Run'), ('COLLAB', 'Collab')], db_index=True, max_length=20),
        ),
    ]
