# Generated by Django 6.0.2 on 2026-02-26 15:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_price_mzn',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Deixe vazio para evento free. Ex: 500.00', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço do ticket (MZN)'),
        ),
    ]
