# Generated by Django 6.0.2 on 2026-02-26 19:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_ticket_price_mzn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Informe um número válido (ex: 84xxxxxxx ou +25884xxxxxxx).', regex='^\\+?\\d{7,15}$')])),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('EMOLA', 'e-Mola'), ('CARD', 'Card')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MZN', max_length=5)),
                ('gateway_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='events.event')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event', 'status'], name='events_orde_event_i_4e9eab_idx'), models.Index(fields=['payment_method', 'status'], name='events_orde_payment_358fd8_idx'), models.Index(fields=['event', 'created_at'], name='events_orde_event_i_f4627e_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'email'), name='uniq_order_event_email')],
            },
        ),
    ]
