# Generated by Django 6.0.2 on 2026-02-27 10:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(editable=False, max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Informe um número válido (ex: 84xxxxxxx ou +25884xxxxxxx).', regex='^\\+?\\d{7,15}$')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='UNPAID', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='events_orde_event_i_4e9eab_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='events_orde_payment_358fd8_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='events_orde_event_i_f4627e_idx',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='uniq_order_event_email',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='ticket_price_mzn',
            new_name='price',
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.event'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'payment_status'], name='events_even_event_i_11380a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['phone'], name='events_even_phone_e3c8e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='uniq_order_event_email'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
