# Generated by Django 6.0.2 on 2026-02-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventregistration_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventregistration',
            name='uniq_order_event_email',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='email',
        ),
    ]
