# Generated by Django 6.0.2 on 2026-02-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventregistration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='email',
        ),
    ]
